function sdrNames = piSDRSceneNames
% Return the names of the SDR scene directories.  Used with piSceneDeposit.
%
% Synopsis
%  sdrNames = piSDRSceneNames
%
% Link to the SDR data
%    https://purl.stanford.edu/cb706yg0989
%
% The scenes are all in the 'ISET 3d scenes' SDR deposit. Within that
% deposit, they are in subdirectories. This list returns the
% subdirectory and name.
%
% sdrNames.subdir.names
%
% NOTE:  The SDR for iset3d is iset3d-scenes.  Need to attend to that
% somehow.
%
%  subdir is one of 'bitterli','pbrtv4','iset3d'
%  names is a cell array of names
%
% This should match the case statements in piRecipeDefault
%
% See also
%   piSceneDeposit, piSceneWebTest, ieWebGet

% Find the scene on the Stanford Digital Repository
names = {'bathroom','bathroom2','bedroom','classroom',...
    'cornell-box','glass-of-water','lamp',...
    'living-room','living-room-2','living-room-3',...
    'staircase','staircase2','teapot-full',...
    'veach-ajar','veach-bidir','veach-mis'};
sdrNames.bitterli.names = names;

names = {'barcelona-pavilion',...
    'bistro', ...
    'bunny-cloud','bunny-fur',...
    'bmw-m6',...
    'clouds','contemporary-bathroom','crown',...
    'dambreak',...
    'disney-cloud','ganesha','hair','head-pbrtv4',...
    'killeroos', 'kitchen','landscape',...
    'lte-orb','pbrt-book','sanmiguel',...
    'smoke-plume','sportscar',...
    'sssdragon','transparent-machines',...
    'zero-day'
    };
sdrNames.pbrtv4.names = names;

names = {'arealight','bunny','car','characters','checkerboard',...
    'chessset','coordinate','cornell_box','cornell-box-iset3d',...
    'cornellboxreference','flashcards',...
    'flatsurface','flatsurfacewhitetexture',...
    'head', ...
    'lettersatdepth','low-poly-taxi','macbethchecker','macbethchart',...
    'materialball','materialball_cloth','simplescene',...
    'slantededge','snellenatdepth','sphere',...
    'stepfunction','teapot-set','testplane'};
sdrNames.iset3d.names = names;

end
