function prefs = prefStruct(obj)
% prefStruct Return normalized preference-like values from this object.

prefs = struct( ...
    'label', getpref('ISETDocker', 'label', obj.label), ...
    'renderContext', obj.renderContext, ...
    'remoteHost', obj.remoteHost, ...
    'device', obj.device, ...
    'deviceID', obj.deviceID, ...
    'dockerImage', obj.dockerImage, ...
    'remoteUser', obj.remoteUser, ...
    'workDir', obj.workDir, ...
    'PBRTResources', getpref('ISETDocker', 'PBRTResources', ''));

if ispref('ISETDocker', 'PBRTContainer')
    prefs.PBRTContainer = getpref('ISETDocker', 'PBRTContainer');
end

if ispref('ISETDocker', 'batch')
    prefs.batch = getpref('ISETDocker', 'batch');
end

end
