% parser test

% thisR = piRead('/Users/zhenyi/git_repo/dev/iset3d-tiny/data/scenes/web/cornell_box/cornell_box.pbrt');
% lightName = 'new_spot_light_L';
% spotLight = piLightCreate(lightName,...
% 'type','spot',...
% 'spd','equalEnergy',...
% 'specscale', 1, ...
% 'coneangle', 15,...
% 'conedeltaangle', 10, ...
% 'cameracoordinate', true);
% thisR.set('light', spotLight, 'add');
% thisR.set('film resolution', [134, 134]);
% scene = piWRS(thisR);
% 
% thisR_pw = piRead('/Users/zhenyi/git_repo/dev/iset3d-tiny/local/cornell_box/cornell_box.pbrt');
% thisR_pw.set('film resolution', [134, 134]);
% 
% scene_pw = piWRS(thisR_pw);
%% Fix these
% Too many assets to parse, might not be a good scene for us to parse with
% iset3d.
% thisR = piRead('/Users/zhenyi/git_repo/pbrt-v4-scenes/landscape/view-0.pbrt');
% Illegal memory access
% thisR = piRead('/Users/zhenyi/git_repo/pbrt-v4-scenes/villa/villa-daylight.pbrt');
% thisR = piRead('/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-1.pbrt');
% thisR = piRead('/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-entry.pbrt');
% thisR = piRead('/Users/zhenyi/git_repo/pbrt-v4-scenes/zero-day/frame25.pbrt');

%%
sceneList = {'/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-2.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-3.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-4.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-5.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-6.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-7.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-8.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-9.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-10.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-11.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-12.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-13.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-14.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-15.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-16.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-17.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/watercolor/camera-18.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-upstairs.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-upstairs-corner.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-upstairs-across.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-realistic-courtyard.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-in-tree.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-entry.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-courtyard.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-courtyard-second.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/sanmiguel/sanmiguel-balcony-plants.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/villa/villa-daylight.pbrt',...
    '/Users/zhenyi/git_repo/pbrt-v4-scenes/villa/villa-lights-on.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/bedroom/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/car/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/classroom/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/coffee/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/cornell-box/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/dining-room/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/glass-of-water/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/kitchen/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/lamp/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/living-room/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/spaceship/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/staircase/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/veach-ajar/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/veach-bidir/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/volumetric-caustic/scene-v4.pbrt',...
    '/Users/zhenyi/git_repo/ben-pbrtv4/water-caustic/scene-v4.pbrt'
    };
for ii = 29:numel(sceneList)
    thisSceneName = erase(sceneList{ii}, '/Users/zhenyi/git_repo/pbrt-v4-scenes/');
    try
        thisR = piRead(sceneList{ii},'exporter','Copy');
        thisR = thisR.set('rays per pixel',1024);
        size = thisR.get('film resolution');
        if min(size)<1200
            if size(1) <= size(2) 
                resolution = round([1200, 1200/min(size) * max(size)]);
            else
                resolution = round([1200/min(size) * max(size), 1200]);
            end
            thisR = thisR.set('film resolution',resolution);
        end
        piWrite(thisR);
        try
            % default render with cpu
            setpref('ISETDocker','device','gpu');
            [ieObject,resultsMsgs] = piRender(thisR,'docker',isetdocker);
        catch
            % it could be a GPU issue, switch to CPU temporary.
            setpref('ISETDocker','device','cpu');
            [ieObject,resultsMsgs] = piRender(thisR,'docker',isetdocker);
        end
        msg{ii} = sprintf('Rendered: %s.\n',thisSceneName);
    catch
        disp(resultsMsgs);
        msg{ii} = sprintf('Failed: %s.\n',thisSceneName);
    end
    % save(fullfile('~/Desktop/SensorDataset',[fileparts(thisSceneName),'.mat']),"ieObject");
end
disp(msg);
%%
% piWrite(thisR);
% [scene] = piRender(thisR, 'docker', isetdocker);
% sceneWindow(scene);
%%
% scene = piAIdenoise(scene);
% sceneWindow(scene);